services:
  - type: web
    name: beevy
    runtime: python
    plan: free
    region: frankfurt
    healthCheckPath: /health
    buildCommand: pip install -r requirements.txt
    startCommand: python scripts/init_db.py ; gunicorn -w 1 --threads 8 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: SECRET_KEY
        generateValue: true
